import { Injectable } from '@angular/core';
import { DailyDemand, CreateDailyDemand } from '../../models/agency/daily-demand';
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://wxryryyiakzkeeoorlrq.supabase.co';
const supabaseKey =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4cnlyeXlpYWt6a2Vlb29ybHJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc2NzY0MTIsImV4cCI6MjEwMzI1MjQxMn0.B8Q_B3diy-hDK37HttpNscXfLcDbSOYpP7A14DlQF8A';
const supabase = createClient(supabaseUrl, supabaseKey);

export async function fetchSupplyItems() {
  const { data, error } = await supabase.from('agency-daily-supply_items').select('*');

  if (error) {
    console.error('抓取物資失敗：', error);
    return [];
  }
  return data;
}

@Injectable({
  providedIn: 'root',
})
export class DailyDemandService {
  demands: DailyDemand[] = [
    {
      id: 1,
      item: '成人乾糧與即食食品組',
      amount: 300,
      remaining: 280,
      unit: '份',
      amountDescription: '每份包含即食飯、罐頭、飲用水及營養補充食品，需適合災區臨時安置家庭使用。',
      category: '食物',
      reason: '因豪雨造成部分地區道路中斷，多戶家庭暫時無法取得正常餐食。',
      description: '希望募集保存期限較長且方便攜帶的食品，優先提供給災區弱勢家庭、老人及行動不便者使用。',
      brand: '不限品牌，但需確認食品包裝完整且未過期。',
      serviceTargets: {
        老人: true,
        嬰幼兒: false,
        孩童: false,
        青少年: false,
        身障: true,
        貧困: true,
        重症照護: false,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['獨居長者'],
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需有完整食品標示'],
      priority: '非常緊急',
      status: '上架',
      receiveMethod: '寄送',
      recipient: '花蓮縣救災資源中心 物資組',
      address: '花蓮縣花蓮市中央路三段100號',
      phone: '03-8230000（請於09:00-17:00聯繫）',
      note: '請於每日09:00至17:00送達。',
      createdAt: '2026-08-01T10:00:00',
      messageCount: 5,
    },
    {
      id: 2,
      item: '成人冬季保暖外套',
      amount: 150,
      remaining: 80,
      unit: '件',
      amountDescription: '男女皆可使用，以M至XL尺寸為主。',
      category: '衣物',
      reason: '寒流造成低收入戶家庭保暖用品不足。',
      description: '需要乾淨且狀況良好的冬季外套，希望協助沒有足夠禦寒衣物的家庭。',
      brand: '不限品牌',
      serviceTargets: {
        老人: true,
        嬰幼兒: false,
        孩童: false,
        青少年: true,
        身障: false,
        貧困: true,
        重症照護: false,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['街友'],
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '',
        毀損: '不接受',
      },
      customConditions: ['需清洗乾淨'],
      priority: '緊急',
      status: '上架',
      receiveMethod: '面交',
      recipient: '',
      address: '台北市萬華區艋舺大道101號（萬華社區服務中心）',
      phone: '02-23000000',
      note: '可接受寄送或現場面交。',
      createdAt: '2026-08-02T09:30:00',
      messageCount: 3,
    },
    {
      id: 3,
      item: '成人醫療口罩',
      amount: 5000,
      remaining: 3500,
      unit: '個',
      amountDescription: '需符合一般醫療防護需求。',
      category: '醫療',
      reason: '災後清理環境需要大量防護用品。',
      description: '因災區清潔工作產生大量粉塵，希望募集醫療口罩供志工及居民使用。',
      brand: '不限品牌',
      serviceTargets: {
        老人: false,
        嬰幼兒: false,
        孩童: false,
        青少年: false,
        身障: false,
        貧困: true,
        重症照護: false,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['災區志工團隊', '現場清潔救援人員'],
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['有效期限至少半年'],
      priority: '緊急',
      status: '上架',
      receiveMethod: '寄送',
      recipient: '台南市安南區應變指揮中心',
      address: '台南市安南區安中路二段50號',
      phone: '06-2550000',
      note: '',
      createdAt: '2026-08-03T14:00:00',
      messageCount: 12,
    },
    {
      id: 4,
      item: '嬰幼兒配方奶粉',
      amount: 100,
      remaining: 65,
      unit: '罐',
      amountDescription: '適合0至1歲嬰幼兒使用。',
      category: '嬰幼兒',
      reason: '部分受災家庭嬰幼兒用品不足。',
      description: '希望募集未拆封奶粉，需確認保存期限充足，提供給育兒家庭使用。',
      brand: '不限品牌',
      serviceTargets: {
        老人: false,
        嬰幼兒: true,
        孩童: false,
        青少年: false,
        身障: false,
        貧困: true,
        重症照護: false,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: [],
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['保存期限一年以上'],
      priority: '非常緊急',
      status: '隱藏',
      receiveMethod: '寄送',
      recipient: '高雄市鳳山區婦幼關懷協會',
      address: '高雄市鳳山區光復路二段120號',
      phone: '07-7000000',
      note: '目前尚未公開募集。',
      messageCount: 0,
    },
    {
      id: 5,
      item: '毛毯與保暖棉被',
      amount: 200,
      remaining: 120,
      unit: '件',
      amountDescription: '單件尺寸需適合成人使用。',
      category: '生活用品',
      reason: '冬季低溫導致避難家庭缺少保暖用品。',
      description: '需要乾淨完整毛毯及棉被，提供給臨時安置中心使用。',
      brand: '',
      serviceTargets: {
        老人: true,
        嬰幼兒: false,
        孩童: true,
        青少年: false,
        身障: false,
        貧困: true,
        重症照護: false,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['安置中心災民'],
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '',
        毀損: '不接受',
      },
      customConditions: ['不可有明顯異味'],
      priority: '普通',
      status: '下架',
      receiveMethod: '面交',
      recipient: '',
      address: '宜蘭縣羅東鎮純精路一段88號（羅東體育館安置點）',
      phone: '03-9540000',
      note: '需求已暫時補足。',
      createdAt: '2026-07-20T12:00:00',
      messageCount: 8,
    },
    {
      id: 6,
      item: '災區飲用水補給組合包（含箱裝大瓶裝純淨水）',
      amount: 1000,
      remaining: 760,
      unit: '箱',
      amountDescription: '每箱24瓶，每瓶1500毫升，適合家庭及避難中心使用。',
      category: '食物',
      reason: '地震造成部分地區供水設備損壞，需要大量乾淨飲用水。',
      description: '希望募集大量未開封飲用水，提供災區居民、救援人員及臨時收容中心使用，需確認包裝完整且無破損。',
      brand: '不限品牌，需符合食品安全規範。',
      serviceTargets: {
        老人: true,
        嬰幼兒: true,
        孩童: true,
        青少年: true,
        身障: true,
        貧困: true,
        重症照護: true,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['山區受困居民'],
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['有效期限至少三個月'],
      priority: '非常緊急',
      status: '下架',
      receiveMethod: '面交',
      recipient: '',
      address: '嘉義縣阿里山鄉樂野村1號（阿里山鄉公所前廣場）',
      phone: '05-2670000',
      note: '大型物資車可直接進入。',
      createdAt: '2026-08-04T08:30:00',
      messageCount: 15,
    },
    {
      id: 7,
      item: '成人長袖衣物',
      amount: 400,
      remaining: 250,
      unit: '件',
      amountDescription: '男女尺寸皆可，主要需求為成人尺寸。',
      category: '衣物',
      reason: '颱風災害後居民衣物遭浸水損壞。',
      description: '募集乾淨長袖衣物，二手衣物可接受，但希望沒有破損、污漬及異味。',
      brand: '不限品牌',
      serviceTargets: {
        老人: false,
        嬰幼兒: false,
        孩童: false,
        青少年: true,
        身障: false,
        貧困: true,
        重症照護: false,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: [],
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '',
        毀損: '不接受',
      },
      customConditions: ['男女皆可'],
      priority: '緊急',
      status: '上架',
      receiveMethod: '寄送',
      recipient: '屏東縣東港鎮救災物資轉運站',
      address: '屏東縣東港鎮沿海路200號',
      phone: '08-8320000',
      note: '',
      createdAt: '2026-08-04T11:00:00',
      messageCount: 7,
    },
    {
      id: 8,
      item: '慢性病患者常用藥品收納盒',
      amount: 80,
      remaining: 50,
      unit: '個',
      amountDescription: '需方便分類每日藥物。',
      category: '醫療',
      reason: '協助災後慢性病患者整理藥物。',
      description: '部分長者因搬遷至避難中心，藥物管理不便，需要簡易藥盒協助分類。',
      brand: '',
      serviceTargets: {
        老人: true,
        嬰幼兒: false,
        孩童: false,
        青少年: false,
        身障: true,
        貧困: false,
        重症照護: true,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['慢性病長者'],
      conditions: {
        全新: '接受',
        二手: '',
        有擦痕: '',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需可清洗'],
      priority: '普通',
      status: '下架',
      receiveMethod: '寄送',
      recipient: '新竹縣尖石鄉衛生所',
      address: '新竹縣尖石鄉嘉樂村2鄰70號',
      phone: '03-5840000',
      note: '',
      createdAt: '2026-08-01T16:20:00',
      messageCount: 2,
    },
    {
      id: 9,
      item: '兒童書籍與學用品',
      amount: 300,
      remaining: 180,
      unit: '組',
      amountDescription: '包含鉛筆、筆記本、彩色筆及兒童讀物。',
      category: '其他',
      reason: '災後部分家庭孩童學習用品遺失。',
      description: '希望募集適合國小至國中的學用品，協助受災家庭孩童恢復正常學習。',
      brand: '不限品牌',
      serviceTargets: {
        老人: false,
        嬰幼兒: false,
        孩童: true,
        青少年: true,
        身障: false,
        貧困: true,
        重症照護: false,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['偏鄉受災學童'],
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '',
        毀損: '不接受',
      },
      customConditions: ['內容物需完整'],
      priority: '普通',
      status: '上架',
      receiveMethod: '寄送',
      recipient: '台中市和平區國小課後照顧班',
      address: '台中市和平區東關路三段1號',
      phone: '04-2590000',
      note: '',
      createdAt: '2026-08-02T13:00:00',
      messageCount: 4,
    },
    {
      id: 10,
      item: '寵物乾糧飼料',
      amount: 200,
      remaining: 100,
      unit: '包',
      amountDescription: '犬貓皆可使用，以乾糧為主。',
      category: '其他',
      reason: '協助災區受困民眾照顧伴侶動物。',
      description: '因部分家庭撤離時無法攜帶足夠寵物用品，希望募集安全乾糧。',
      brand: '不限品牌',
      serviceTargets: {
        老人: false,
        嬰幼兒: false,
        孩童: false,
        青少年: false,
        身障: false,
        貧困: false,
        重症照護: false,
        寵物: true,
        流浪: true,
        野生: false,
      },
      customServiceTargets: [],
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需標示保存期限'],
      priority: '緊急',
      status: '隱藏',
      receiveMethod: '面交',
      recipient: '',
      address: '台東縣成功鎮中華路50號（成功鎮動保收容據點）',
      phone: '089-850000',
      note: '',
      messageCount: 6,
    },
    {
      id: 11,
      item: '災區緊急照明與備用電源設備',
      amount: 150,
      remaining: 90,
      unit: '組',
      amountDescription: '包含LED緊急照明燈、手搖發電手電筒及大容量行動電源。',
      category: '生活用品',
      reason: '強烈風災導致山區部落連續多日停電，影響夜間安全與通訊需求。',
      description: '募集可充式或手搖式應急燈具，以及能夠為手機充電之行動電源，優先提供給電力尚未恢復之山區安置點及長者家庭使用。',
      brand: '不限品牌，但需通過相關安全認證。',
      serviceTargets: {
        老人: true,
        嬰幼兒: false,
        孩童: false,
        青少年: false,
        身障: true,
        貧困: true,
        重症照護: false,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['停電山區部落居民'],
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '',
        毀損: '不接受',
      },
      customConditions: ['蓄電功能需正常', '需附充電線材'],
      priority: '非常緊急',
      status: '下架',
      receiveMethod: '寄送',
      recipient: '南投縣信義鄉物資收容中心',
      address: '南投縣信義鄉玉山路55號',
      phone: '049-2790000',
      note: '大型物資車可直接進入。',
      createdAt: '2026-08-04T08:30:00',
      messageCount: 15,
    },
    {
      id: 12,
      item: '嬰幼兒保暖包屁衣與保暖毯組合',
      amount: 250,
      remaining: 180,
      unit: '套',
      amountDescription: '包含0-2歲嬰幼兒保暖包屁衣、長褲及小毛毯，尺寸註明於外包裝。',
      category: '嬰幼兒',
      reason: '災後收容中心氣溫驟降，嬰幼兒禦寒衣物不足。',
      description: '希望募集乾淨無污漬之嬰幼兒保暖衣服，幫助暫住安置中心之新手媽媽與幼童度過寒冷夜晚。',
      brand: '不限品牌，以棉質舒適材質為主。',
      serviceTargets: {
        老人: false,
        嬰幼兒: true,
        孩童: false,
        青少年: false,
        身障: false,
        貧困: true,
        重症照護: false,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['安置中心新手媽媽'],
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '',
        毀損: '不接受',
      },
      customConditions: ['無過敏原', '二手需無黃斑或污漬'],
      priority: '緊急',
      status: '隱藏',
      receiveMethod: '寄送',
      recipient: '屏東縣三地門鄉救災中心',
      address: '屏東縣三地門鄉行政路1號',
      phone: '08-7990000',
      note: '',
      messageCount: 7,
    },
    {
      id: 13,
      item: '成人替換式紙尿褲與照護墊',
      amount: 500,
      remaining: 320,
      unit: '包',
      amountDescription: 'L至XL號成人復健褲與防水照護墊，每包約10-20片。',
      category: '生活用品',
      reason: '避難所內臥床長者與行動不便身障者衛材消耗迅速，庫存告急。',
      description: '緊急募集成人紙尿褲與看護墊，以維持臥床長者之衛生清潔與舒適，避免發生褥瘡或感染。',
      brand: '不限品牌',
      serviceTargets: {
        老人: true,
        嬰幼兒: false,
        孩童: false,
        青少年: false,
        身障: true,
        貧困: true,
        重症照護: true,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['臥床長者'],
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['包裝需完整未拆封'],
      priority: '非常緊急',
      status: '上架',
      receiveMethod: '面交',
      recipient: '',
      address: '新竹縣五峰鄉活動中心（避難收容所）',
      phone: '03-5850000',
      note: '現場參觀或交付請先聯繫確認時間。',
      createdAt: '2026-08-01T16:20:00',
      messageCount: 2,
    },
    {
      id: 14,
      item: '高熱量營養補充飲品',
      amount: 600,
      remaining: 400,
      unit: '罐',
      amountDescription: '每罐250ml，適合無法正常進食之長者或病患補充熱量。',
      category: '食物',
      reason: '安置中心部分高齡長者因牙口不佳，難以消化普通乾糧物資。',
      description: '募集知名品牌高熱量營養補充飲品，幫助災區長者及重症照護對象保持體力與營養平衡。',
      brand: '不限品牌，如亞培安素、補體素等。',
      serviceTargets: {
        老人: true,
        嬰幼兒: false,
        孩童: false,
        青少年: false,
        身障: true,
        貧困: false,
        重症照護: true,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['咀嚼困難長者'],
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['保存期限至少四個月以上'],
      priority: '緊急',
      status: '下架',
      receiveMethod: '寄送',
      recipient: '台中市和平區長照關懷協會',
      address: '台中市和平區東關路一段100號',
      phone: '04-2590000',
      note: '',
      createdAt: '2026-08-02T13:00:00',
      messageCount: 4,
    },
    {
      id: 15,
      item: '流浪動物急救醫療防護專用軟膏與繃帶',
      amount: 100,
      remaining: 60,
      unit: '盒',
      amountDescription: '包含動物用創傷消毒噴劑、自黏性彈性繃帶及消炎軟膏。',
      category: '醫療',
      reason: '颱風過後流浪動物遭外物割傷或摔傷，急需基本醫藥物資治療。',
      description: '募集動物專用醫療護理包，供在地動保志工於災區進行外傷包紮與緊急救護使用。',
      brand: '不限品牌，需為獸醫或動保專用品。',
      serviceTargets: {
        老人: false,
        嬰幼兒: false,
        孩童: false,
        青少年: false,
        身障: false,
        貧困: false,
        重症照護: false,
        寵物: false,
        流浪: true,
        野生: true,
      },
      customServiceTargets: ['災區受傷野生與流浪動物'],
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['藥品需標示清楚用途與效期'],
      priority: '普通',
      status: '隱藏',
      receiveMethod: '寄送',
      recipient: '台東縣關山鎮動保救援志工團',
      address: '台東縣關山鎮博愛路20號',
      phone: '089-810000',
      note: '',
      messageCount: 6,
    },
    {
      id: 16,
      item: '災區臨時安置家庭急需大型綜合生活補給物資組合包（包含成人與兒童使用之日常生活用品、清潔用品、簡易餐具、衛生用品、照明用品以及其他因災害造成家庭生活中斷後所需要補充的基本用品）',
      amount: 50,
      remaining: 50,
      unit: '組',
      amountDescription: '每組提供一戶受災家庭約一週生活所需用品，包含衛生紙、清潔劑、洗髮精、沐浴乳、牙膏牙刷、毛巾及隨身照明燈具。',
      category: '生活用品',
      reason:
        '因強烈地震造成房屋嚴重倒塌與結構受損，多戶家庭被迫緊急撤離並入住臨時收容中心，無法返回原居住地拿取個人物品。由於生活用品全面缺乏，導致居民日常衛生與基本生活遭遇重大困難，亟需外界支援完整補給包以渡過當前難關。',
      description:
        '希望募集完整生活補給組合包，內容包含家庭日常所需用品，需適合老人、孩童及身心障礙者使用，並希望物品皆保持良好狀態。本次募集旨在為受災戶提供最基本的尊嚴與衛生保障，所有收到之物資將由工作人員依據各戶實際人口數進行點收、登記與發放。若您所提供的物資中有易碎物品或液體容器，請務必進行適當包裝與固定，避免在運輸過程中發生滲漏或破損。',
      brand: '不限品牌，但需符合國內相關安全及品質衛生標準，且包裝完整無破損。',
      serviceTargets: {
        老人: true,
        嬰幼兒: true,
        孩童: true,
        青少年: true,
        身障: true,
        貧困: true,
        重症照護: true,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['房屋倒塌受災戶', '臨時避難所整戶家庭'],
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需分類包裝', '大型物品請先聯絡確認'],
      priority: '非常緊急',
      status: '上架',
      receiveMethod: '寄送',
      recipient: '高雄市旗山區災後聯合物資調度中心 儲運組',
      address: '高雄市旗山區延平一路300號（旗山區公所後方倉庫）',
      phone: '07-6600000（服務時間：週一至週日 08:00-20:00）',
      note: '此需求為災後大型家庭補給專案，若一次提供大量物資請提前聯繫，以方便安排倉儲空間、分類整理以及後續配送流程。',
      createdAt: '2026-08-06T09:00:00',
      messageCount: 20,
    },
    {
      id: 17,
      item: '災區兒童臨時照護玩具與心理安撫用品組',
      amount: 120,
      remaining: 45,
      unit: '組',
      amountDescription: '每組包含繪本、益智玩具、彩色筆及簡易遊戲用品。',
      category: '嬰幼兒',
      reason: '災害期間部分兒童因生活環境改變產生不安，需要透過活動用品協助情緒安撫。',
      description: '募集適合幼兒及兒童使用的安全玩具與閱讀用品，希望協助臨時安置中心提供安心的活動空間。',
      brand: '不限品牌，需符合兒童用品安全標準。',
      serviceTargets: {
        老人: false,
        嬰幼兒: true,
        孩童: true,
        青少年: false,
        身障: false,
        貧困: false,
        重症照護: false,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['安置中心受驚嚇兒童'],
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '',
        毀損: '不接受',
      },
      customConditions: ['不可有尖銳零件'],
      priority: '緊急',
      status: '上架',
      receiveMethod: '面交',
      recipient: '',
      address: '苗栗縣南庄鄉文化路15號（南庄國小活動中心）',
      phone: '037-823000',
      note: '若為二手用品請先清潔消毒。',
      createdAt: '2026-08-04T15:30:00',
      messageCount: 9,
    },
    {
      id: 18,
      item: '身心障礙者專用輔助用品與生活支援設備',
      amount: 60,
      remaining: 22,
      unit: '件',
      amountDescription: '包含助行用品、防滑用品及日常生活輔助設備。',
      category: '醫療',
      reason: '部分身心障礙居民因災害造成原有輔具損壞，需要緊急替代用品。',
      description: '希望募集適合身心障礙者使用的輔助用品，需確認功能正常，方便受災民眾恢復日常生活。',
      brand: '不限品牌，可接受不同規格型號。',
      serviceTargets: {
        老人: true,
        嬰幼兒: false,
        孩童: false,
        青少年: false,
        身障: true,
        貧困: false,
        重症照護: true,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['輔具受損身障災民'],
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '',
        毀損: '不接受',
      },
      customConditions: ['需附使用說明'],
      priority: '非常緊急',
      status: '隱藏',
      receiveMethod: '寄送',
      recipient: '南投縣埔里鎮身心障礙福利協進會',
      address: '南投縣埔里鎮中山路二段200號',
      phone: '049-2900000',
      note: '大型輔具請提前預約搬運。',
      messageCount: 14,
    },
    {
      id: 19,
      item: '災後環境清潔消毒用品補充需求',
      amount: 300,
      remaining: 0,
      unit: '組',
      amountDescription: '每組包含垃圾袋、清潔劑、手套、刷具及消毒用品。',
      category: '生活用品',
      reason: '災後家園清理工作完成，目前物資需求已達標。',
      description: '此需求原用於協助居民進行環境整理，目前剩餘數量為零，保留資料供後續需求紀錄與統計使用。',
      brand: '',
      serviceTargets: {
        老人: false,
        嬰幼兒: false,
        孩童: false,
        青少年: false,
        身障: false,
        貧困: true,
        重症照護: false,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['淹水家園重建戶'],
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需具有完整包裝'],
      priority: '普通',
      status: '下架',
      receiveMethod: '寄送',
      recipient: '新北市瑞芳區公所清潔隊物資組',
      address: '新北市瑞芳區逢甲路88號',
      phone: '02-24970000',
      note: '需求已完成，因此暫停募集。',
      createdAt: '2026-07-25T10:30:00',
      messageCount: 30,
    },
    {
      id: 20,
      item: '野生動物救援臨時收容所專用飼料與醫療照護用品',
      amount: 150,
      remaining: 90,
      unit: '箱',
      amountDescription: '包含動物飼料、飲水用品及基本照護用品。',
      category: '其他',
      reason: '天然災害造成野生動物棲地受損，需要協助救援與安置。',
      description: '募集提供給野生動物救援單位使用之相關用品，需確認適合動物使用且保存期限充足。',
      brand: '不限品牌，需標示成分。',
      serviceTargets: {
        老人: false,
        嬰幼兒: false,
        孩童: false,
        青少年: false,
        身障: false,
        貧困: false,
        重症照護: false,
        寵物: false,
        流浪: false,
        野生: true,
      },
      customServiceTargets: ['災區受傷野生保育類動物'],
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需適合多種類動物使用'],
      priority: '緊急',
      status: '隱藏',
      receiveMethod: '面交',
      recipient: '',
      address: '花蓮縣壽豐鄉大學路二段1號（東華大學野生動物救傷中心）',
      phone: '03-8650000',
      note: '目前尚未公開募集，等待救援單位確認。',
      messageCount: 0,
    },
  ];

  // 🚀 改良版的 getDemands：優先從 Supabase 抓，抓不到或失敗就退回使用假資料
  async getDemands(): Promise<DailyDemand[]> {
    const { data, error } = await supabase.from('agency-daily-supply_items').select('*');

    // 🔍 加上這兩行來抓戰犯
    console.log('Supabase 回傳的 error:', error);
    console.log('Supabase 回傳的 data:', data);

    if (error || !data || data.length === 0) {
      console.warn('⚠️ 無法從 Supabase 取得資料，改用本地假資料：', error);
      return this.demands;
    }

    // 如果 Supabase 有資料，您可以把資料對應成您需要的格式回傳
    return data as DailyDemand[];
  }

  addDemand(demand: CreateDailyDemand) {
    this.demands.push({
      ...demand,
      id: this.demands.length + 1,
    });
  }
  //getDemands() {
  //  return this.demands;
  //}

  // 新增：根據 ID 從 Supabase（或本地陣列）抓取單筆資料
  async getDemandByIdAsync(id: number): Promise<DailyDemand | undefined> {
    const demands = await this.getDemands();
    return demands.find((demand) => demand.id === id);
  }

  getDemandById(id: number): DailyDemand | undefined {
    return this.demands.find((demand) => demand.id === id);
  }

  updateDemand(updatedDemand: DailyDemand) {
    const index = this.demands.findIndex((item) => item.id === updatedDemand.id);

    if (index !== -1) {
      this.demands[index] = updatedDemand;
    }
  }

  deleteDemand(id: number) {
    this.demands = this.demands.filter((item) => item.id !== id);
  }
}
