import { Injectable } from '@angular/core';
import { DisasterDemand, CreateDisasterDemand } from '../../models/agency/demand';

@Injectable({
  providedIn: 'root',
})
export class DisasterDemandService {
  demands: DisasterDemand[] = [
    {
      id: 1,
      item: '礦泉水',
      amount: 500,
      unit: '箱',
      amountDescription: '每箱24瓶，每瓶600毫升，提供災區避難收容所飲用及基本生活使用。',
      reason: '近期災害造成部分地區供水及民生物資運輸受影響，目前避難收容人數增加，飲用水消耗量大幅提高。',
      description: '以未開封且保存期限充足之瓶裝飲用水為主，外箱不得有嚴重破損或受潮情形。',
      brand: '不限品牌，以符合食品安全規範之瓶裝水為主。',
      category: '食品與飲用水',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '不接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['保存期限至少六個月'],
      priority: '非常緊急',
      status: '上架',
      remaining: 320,
      address: '宜蘭縣災害物資集中收受中心',
      phone: '039123456',
      contactTimeWeekday: true,
      contactTimeWeekend: true,
      contactTimeMorning: true,
      contactTimeAfternoon: true,
      contactTimeEvening: true,
      note: '請優先協助配送至目前物資短缺的避難收容場所。',
      image: [],
      imageFileNames: [],
      createdAt: '2026-08-20T09:00:00',
      publishedAt: '2026-08-20T09:00:00',
      expectedOffShelfAt: '2026-08-27T09:00:00',
    },

    {
      id: 2,
      item: '即食白粥及營養粥',
      amount: 300,
      unit: '箱',
      amountDescription: '每箱約12～24份，可依包裝規格提供單人份即食食品。',
      reason: '災區部分居民無法正常使用瓦斯及電力設備，需要容易開封及食用的即食食品。',
      description: '以常溫保存、不需冷藏及簡易加熱即可食用之食品為佳，並請確認包裝完整。',
      brand: '不限品牌。',
      category: '食品與飲用水',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['低鹽、低油、適合長者食用'],
      priority: '緊急',
      status: '上架',
      remaining: 180,
      address: '宜蘭縣災害物資集中收受中心',
      phone: '039234567',
      contactTimeWeekday: true,
      contactTimeWeekend: false,
      contactTimeMorning: true,
      contactTimeAfternoon: true,
      contactTimeEvening: false,
      note: '食品請確認保存期限及外包裝完整。',
      image: [
  'https://images.unsplash.com/photo-1548839140-29a749e1cf4d',
  'https://images.unsplash.com/photo-1523362628745-0c100150b504',
  'https://images.unsplash.com/photo-1550507992-eb63ffee0847'
],
      imageFileNames: [],
      createdAt: '2026-08-21T10:30:00',
      publishedAt: '2026-08-21T10:30:00',
      expectedOffShelfAt: '2026-09-04T10:30:00',
    },

    {
      id: 3,
      item: '成人保暖外套',
      amount: 200,
      unit: '件',
      amountDescription: '成人男女皆可穿著，以M～XL尺寸為主。',
      reason: '災後臨時安置場所夜間溫度較低，部分受災居民衣物於撤離過程中遺失或損壞。',
      description: '希望提供乾淨、完整且適合成人穿著的外套，尺寸以常見成人尺寸為主。',
      brand: '不限品牌。',
      category: '衣物與保暖用品',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['請先清洗並確認無明顯異味'],
      priority: '普通',
      status: '上架',
      remaining: 125,
      address: '宜蘭縣冬山鄉臨時安置中心',
      phone: '039345678',
      contactTimeWeekday: true,
      contactTimeWeekend: true,
      contactTimeMorning: false,
      contactTimeAfternoon: true,
      contactTimeEvening: true,
      note: '成人男女外套皆可。',
      image: [],
      imageFileNames: [],
      createdAt: '2026-08-22T08:30:00',
      publishedAt: '2026-08-22T08:30:00',
      expectedOffShelfAt: '2026-09-21T08:30:00',
    },

    {
      id: 4,
      item: '防寒毛毯',
      amount: 350,
      unit: '條',
      amountDescription: '每條約150×200公分，方便一名成人使用。',
      reason: '臨時避難場所床位及保暖物資不足，需要補充防寒用品。',
      description: '尺寸不拘但以成人使用規格為佳，需保持乾燥。',
      brand: '不限品牌。',
      category: '衣物與保暖用品',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['可接受輕微使用痕跡', '不可有霉味', '不可受潮'],
      priority: '非常緊急',
      status: '上架',
      remaining: 210,
      address: '宜蘭縣羅東鎮臨時避難中心',
      phone: '039456789',
      contactTimeWeekday: false,
      contactTimeWeekend: true,
      contactTimeMorning: false,
      contactTimeAfternoon: true,
      contactTimeEvening: true,
      note: '請保持毛毯乾燥。',
      image: [],
      imageFileNames: [],
      createdAt: '2026-08-23T11:00:00',
      publishedAt: '2026-08-23T11:00:00',
      expectedOffShelfAt: '2026-08-30T11:00:00',
    },

    {
      id: 5,
      item: '外傷急救包',
      amount: 100,
      unit: '組',
      amountDescription: '每組包含基本消毒用品、紗布、繃帶、透氣膠帶及常用急救用品。',
      reason: '災後清理環境期間容易發生割傷、擦傷及其他輕微外傷，需要補充現場急救用品。',
      description: '以完整未拆封之急救用品為主，醫療耗材需確認保存期限。',
      brand: '不限品牌，但醫療用品需有合法標示。',
      category: '醫療與照護用品',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '不接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需有清楚保存期限', '包裝需完整'],
      priority: '非常緊急',
      status: '上架',
      remaining: 38,
      address: '宜蘭縣醫療物資集中收受站',
      phone: '039567890',
      contactTimeWeekday: true,
      contactTimeWeekend: true,
      contactTimeMorning: true,
      contactTimeAfternoon: true,
      contactTimeEvening: true,
      note: '醫療用品請勿提供已開封產品。',
      image: [],
      imageFileNames: [],
      createdAt: '2026-08-24T08:00:00',
      publishedAt: '2026-08-24T08:00:00',
      expectedOffShelfAt: '2026-08-31T08:00:00',
    },

    {
      id: 6,
      item: '成人紙尿褲 M 號',
      amount: 80,
      unit: '箱',
      amountDescription: '以成人M號為主，每箱約8～12包。',
      reason: '部分受災長者及行動不便居民需要持續使用照護用品，現有庫存不足。',
      description: '希望提供成人紙尿褲M號，吸收力正常且包裝完整。',
      brand: '不限品牌。',
      category: '醫療與照護用品',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '不接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['M號優先', '需有獨立包裝'],
      priority: '緊急',
      status: '上架',
      remaining: 47,
      address: '宜蘭縣長者照護物資站',
      phone: '039678901',
      contactTimeWeekday: true,
      contactTimeWeekend: false,
      contactTimeMorning: true,
      contactTimeAfternoon: true,
      contactTimeEvening: false,
      note: '請勿提供已拆封或受潮產品。',
      image: [],
      imageFileNames: [],
      createdAt: '2026-08-24T13:00:00',
      publishedAt: '2026-08-24T13:00:00',
      expectedOffShelfAt: '2026-09-07T13:00:00',
    },

    {
      id: 7,
      item: '酒精濕紙巾',
      amount: 500,
      unit: '包',
      amountDescription: '每包至少20～30抽，方便避難場所及物資站清潔使用。',
      reason: '災後公共空間人員集中，需加強環境及手部清潔，現有清潔用品消耗速度較快。',
      description: '以完整包裝、未過期之酒精濕紙巾為主，可接受不同規格。',
      brand: '不限品牌。',
      category: '清潔與衛生用品',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '接受',
      },
      customConditions: ['酒精成分需清楚標示', '不可有明顯乾涸'],
      priority: '緊急',
      status: '上架',
      remaining: 290,
      address: '宜蘭縣災後清潔物資站',
      phone: '039789012',
      contactTimeWeekday: true,
      contactTimeWeekend: true,
      contactTimeMorning: true,
      contactTimeAfternoon: true,
      contactTimeEvening: false,
      note: '請確認包裝沒有破損。',
      image: [],
      imageFileNames: [],
      createdAt: '2026-08-24T14:00:00',
      publishedAt: '2026-08-24T14:00:00',
      expectedOffShelfAt: '2026-09-07T14:00:00',
    },

    {
      id: 8,
      item: '嬰兒紙尿布 M 號',
      amount: 120,
      unit: '箱',
      amountDescription: '嬰兒M號紙尿布，每箱約3～4包。',
      reason: '避難收容場所目前有多名嬰幼兒家庭，嬰兒基本照護用品消耗快速。',
      description: '以未拆封、保存完整的嬰兒紙尿布為主，M號優先。',
      brand: '不限品牌。',
      category: '嬰幼兒用品',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '不接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['M號優先', '需適合嬰幼兒肌膚使用'],
      priority: '非常緊急',
      status: '上架',
      remaining: 56,
      address: '宜蘭縣嬰幼兒臨時照護中心',
      phone: '039890123',
      contactTimeWeekday: true,
      contactTimeWeekend: true,
      contactTimeMorning: true,
      contactTimeAfternoon: true,
      contactTimeEvening: true,
      note: '請以未拆封產品為主。',
      image: [],
      imageFileNames: [],
      createdAt: '2026-08-25T08:00:00',
      publishedAt: '2026-08-25T08:00:00',
      expectedOffShelfAt: '2026-09-01T08:00:00',
    },

    {
      id: 9,
      item: '成人紙尿褲 L 號',
      amount: 150,
      unit: '箱',
      amountDescription: '成人L號，每箱約8～12包。',
      reason: '目前收容長者照護用品暫時充足，預計後續視實際需求再重新開放。',
      description: '目前暫不急需補充，但保留需求資料供後續物資調度使用。',
      brand: '不限品牌。',
      category: '長者與身心障礙用品',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '不接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['L號優先'],
      priority: '緊急',
      status: '隱藏',
      remaining: 150,
      address: '宜蘭縣長者照護物資站',
      phone: '039901234',
      contactTimeWeekday: true,
      contactTimeWeekend: false,
      contactTimeMorning: true,
      contactTimeAfternoon: true,
      contactTimeEvening: false,
      note: '目前暫停募集。',
      image: [],
      imageFileNames: [],
      createdAt: '2026-08-18T09:00:00',
    },

    {
      id: 10,
      item: '女性生理用品衛生棉',
      amount: 100,
      unit: '箱',
      amountDescription: '日用及夜用衛生棉皆可，每箱依實際包裝數量計算。',
      reason: '災害撤離後部分女性未能攜帶足夠個人衛生用品，需要補充女性生理用品。',
      description: '以獨立包裝、未拆封、未過期產品為主，日用及夜用皆有需求。',
      brand: '不限品牌。',
      category: '女性生理用品',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '不接受',
        過期: '不接受',
        毀損: '接受',
      },
      customConditions: ['日用與夜用皆可', '獨立包裝優先'],
      priority: '緊急',
      status: '上架',
      remaining: 62,
      address: '宜蘭縣婦女物資收受站',
      phone: '039012345',
      contactTimeWeekday: true,
      contactTimeWeekend: true,
      contactTimeMorning: false,
      contactTimeAfternoon: true,
      contactTimeEvening: true,
      note: '請將日用與夜用產品分開標示。',
      image: [],
      imageFileNames: [],
      createdAt: '2026-08-25T09:00:00',
      publishedAt: '2026-08-25T09:00:00',
      expectedOffShelfAt: '2026-09-08T09:00:00',
    },

    {
      id: 11,
      item: '狗飼料',
      amount: 100,
      unit: '袋',
      amountDescription: '成犬乾飼料，每袋約10～15公斤。',
      reason: '災後部分飼主帶著寵物撤離，臨時安置場所需要補充犬隻基本飼料。',
      description: '以成犬乾飼料為主，可接受不同品牌及口味，但不得過期或包裝破損。',
      brand: '不限品牌。',
      category: '寵物與動物用品',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['成犬飼料優先', '不可有受潮情形'],
      priority: '普通',
      status: '上架',
      remaining: 73,
      address: '宜蘭縣流浪動物臨時安置站',
      phone: '039123678',
      contactTimeWeekday: true,
      contactTimeWeekend: false,
      contactTimeMorning: false,
      contactTimeAfternoon: true,
      contactTimeEvening: true,
      note: '請標示飼料適用犬隻年齡。',
      image: [],
      imageFileNames: [],
      createdAt: '2026-08-24T15:00:00',
      publishedAt: '2026-08-24T15:00:00',
      expectedOffShelfAt: '2026-09-23T15:00:00',
    },

    {
      id: 12,
      item: 'LED 手電筒',
      amount: 250,
      unit: '支',
      amountDescription: '攜帶式LED手電筒，每支需可正常開關及照明。',
      reason: '部分災區停電，夜間巡查及居民移動時缺乏基本照明設備。',
      description: '以攜帶方便、操作簡單且可使用一般電池的手電筒為佳。',
      brand: '不限品牌。',
      category: '防災與照明用品',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需附電池', '可接受輕微外觀刮痕'],
      priority: '非常緊急',
      status: '上架',
      remaining: 90,
      address: '宜蘭縣災害防災物資站',
      phone: '039234678',
      contactTimeWeekday: true,
      contactTimeWeekend: true,
      contactTimeMorning: false,
      contactTimeAfternoon: true,
      contactTimeEvening: true,
      note: '請確認每支手電筒均可正常使用。',
      image: [],
      imageFileNames: [],
      createdAt: '2026-08-25T10:00:00',
      publishedAt: '2026-08-25T10:00:00',
      expectedOffShelfAt: '2026-09-01T10:00:00',
    },

    {
      id: 13,
      item: '行動電源',
      amount: 150,
      unit: '個',
      amountDescription: '容量10,000mAh以上之行動電源。',
      reason: '災區停電期間手機及通訊設備無法正常充電，影響居民聯絡家人及接收災情資訊。',
      description: '希望提供容量足夠且可正常充放電之行動電源，USB輸出介面為佳。',
      brand: '不限品牌，但需確認產品安全性。',
      category: '通訊與求救用品',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '不接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['容量至少10000mAh', '需可正常充電', '需附充電線'],
      priority: '非常緊急',
      status: '上架',
      remaining: 42,
      address: '宜蘭縣災害通訊物資站',
      phone: '039345678',
      contactTimeWeekday: true,
      contactTimeWeekend: true,
      contactTimeMorning: true,
      contactTimeAfternoon: true,
      contactTimeEvening: true,
      note: '請確認行動電源沒有膨脹或異常發熱。',
      image: [],
      imageFileNames: [],
      createdAt: '2026-08-25T10:30:00',
      publishedAt: '2026-08-25T10:30:00',
      expectedOffShelfAt: '2026-09-01T10:30:00',
    },

    {
      id: 14,
      item: '卡式瓦斯爐',
      amount: 80,
      unit: '台',
      amountDescription: '家用攜帶式卡式瓦斯爐，每台需附完整爐具及安全裝置。',
      reason: '災後部分地區電力及固定瓦斯供應尚未恢復，需要簡易炊煮設備提供居民使用。',
      description: '以功能正常、結構完整且安全裝置正常之卡式瓦斯爐為主。',
      brand: '不限品牌。',
      category: '生活與炊事用品',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需確認點火功能正常', '不可有瓦斯洩漏問題'],
      priority: '緊急',
      status: '上架',
      remaining: 31,
      address: '宜蘭縣災害生活物資站',
      phone: '039456789',
      contactTimeWeekday: true,
      contactTimeWeekend: false,
      contactTimeMorning: true,
      contactTimeAfternoon: true,
      contactTimeEvening: false,
      note: '二手設備需先確認安全性。',
      image: [],
      imageFileNames: [],
      createdAt: '2026-08-24T16:00:00',
      publishedAt: '2026-08-24T16:00:00',
      expectedOffShelfAt: '2026-09-07T16:00:00',
    },

    {
      id: 15,
      item: '臨時居住帳篷',
      amount: 50,
      unit: '頂',
      amountDescription: '至少可供2～4人臨時休息使用之防水帳篷。',
      reason: '部分受災戶住宅暫時無法居住，需要臨時遮蔽及基本住宿空間。',
      description: '希望提供完整帳篷、支架及固定配件，具備基本防雨功能。',
      brand: '不限品牌。',
      category: '居住安置與修繕用品',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需具防水功能', '配件需完整', '可接受輕微使用痕跡', '不可有破洞', '不可嚴重發霉'],
      priority: '非常緊急',
      status: '上架',
      remaining: 18,
      address: '宜蘭縣災民臨時安置中心',
      phone: '039567890',
      contactTimeWeekday: true,
      contactTimeWeekend: true,
      contactTimeMorning: true,
      contactTimeAfternoon: true,
      contactTimeEvening: true,
      note: '大型物資請事先電話聯繫確認配送方式。',
      image: [],
      imageFileNames: [],
      createdAt: '2026-08-25T11:00:00',
      publishedAt: '2026-08-25T11:00:00',
      expectedOffShelfAt: '2026-09-01T11:00:00',
    },

    {
      id: 16,
      item: '折疊桌椅',
      amount: 60,
      unit: '組',
      amountDescription: '每組包含折疊桌1張及折疊椅4張。',
      reason: '臨時收容場所需要增加用餐及行政作業使用之桌椅。',
      description: '目前暫無立即需求，後續若收容人數增加將重新開放募集。',
      brand: '不限品牌。',
      category: '其他',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '接受',
      },
      customConditions: ['可接受正常使用痕跡'],
      priority: '普通',
      status: '隱藏',
      remaining: 60,
      address: '宜蘭縣臨時收容行政中心',
      phone: '039678901',
      contactTimeWeekday: true,
      contactTimeWeekend: false,
      contactTimeMorning: false,
      contactTimeAfternoon: true,
      contactTimeEvening: false,
      note: '目前暫停募集，後續視需求重新上架。',
      image: [],
      imageFileNames: [],
      createdAt: '2026-08-19T10:00:00',
    },

    {
      id: 17,
      item: '罐頭食品綜合箱',
      amount: 400,
      unit: '箱',
      amountDescription: '每箱約24～48罐，可包含魚罐頭、肉類罐頭及蔬菜罐頭。',
      reason: '災區部分家庭暫時無法正常烹煮，需要容易保存及食用的常溫食品。',
      description: '希望提供保存期限充足、外罐無鏽蝕及凹損之罐頭食品。',
      brand: '不限品牌。',
      category: '食品與飲用水',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['保存期限至少六個月', '不可有罐體膨脹'],
      priority: '普通',
      status: '上架',
      remaining: 400,
      address: '宜蘭縣災害食品物資站',
      phone: '039789012',
      contactTimeWeekday: true,
      contactTimeWeekend: true,
      contactTimeMorning: true,
      contactTimeAfternoon: true,
      contactTimeEvening: false,
      note: '請依食品種類分類裝箱。',
      image: [],
      imageFileNames: [],
      createdAt: '2026-08-25T11:30:00',
      publishedAt: '2026-08-25T11:30:00',
      expectedOffShelfAt: '2026-09-24T11:30:00',
    },

    {
      id: 18,
      item: '防水帆布及修繕材料',
      amount: 100,
      unit: '組',
      amountDescription: '每組包含防水帆布、固定繩、束帶及基本修繕用品。',
      reason: '部分民宅屋頂及門窗於災害中受損，需要先使用防水材料進行臨時遮蔽及修繕。',
      description: '防水帆布尺寸以3×4公尺以上為佳，並希望附有可固定之繩索或相關配件。',
      brand: '不限品牌。',
      category: '居住安置與修繕用品',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需具基本防水功能', '不可有破洞'],
      priority: '緊急',
      status: '上架',
      remaining: 27,
      address: '宜蘭縣災後住宅修繕物資站',
      phone: '039890123',
      contactTimeWeekday: true,
      contactTimeWeekend: true,
      contactTimeMorning: true,
      contactTimeAfternoon: true,
      contactTimeEvening: true,
      note: '大型帆布請事前聯絡，以便安排搬運。',
      image: [],
      imageFileNames: [],
      createdAt: '2026-08-25T12:00:00',
      publishedAt: '2026-08-25T12:00:00',
      expectedOffShelfAt: '2026-09-08T12:00:00',
    },

    {
      id: 19,
      item: '緊急醫療照護用品綜合包',
      amount: 75,
      unit: '組',
      amountDescription: '每組包含紗布、繃帶、醫療膠帶、消毒用品及基本照護耗材。',
      reason: '本次災害期間已募集到足夠數量，目前醫療照護用品暫無新增需求，因此結束募集。',
      description: '本筆需求已完成階段性物資募集，後續將依實際災情及庫存狀況重新評估。',
      brand: '不限品牌。',
      category: '醫療與照護用品',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '不接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['醫療耗材需有完整標示'],
      priority: '非常緊急',
      status: '下架',
      remaining: 0,
      address: '宜蘭縣醫療物資集中收受站',
      phone: '039012678',
      contactTimeWeekday: true,
      contactTimeWeekend: false,
      contactTimeMorning: true,
      contactTimeAfternoon: true,
      contactTimeEvening: false,
      note: '本筆需求已完成募集。',
      image: [],
      imageFileNames: [],
      createdAt: '2026-08-18T08:00:00',
      publishedAt: '2026-08-18T08:00:00',
      expectedOffShelfAt: '2026-08-25T13:00:00',
    },

    {
      id: 20,
      item: '災後環境清潔用品綜合組',
      amount: 200,
      unit: '組',
      amountDescription: '每組包含垃圾袋、掃把、畚箕、手套、抹布及基本清潔用品。',
      reason: '災後環境整理產生大量垃圾及泥沙，需要補充清潔工具供居民及志工進行環境復原。',
      description: '希望提供耐用且容易清洗之清潔工具，手套需有基本防護能力。',
      brand: '不限品牌。',
      category: '清潔與衛生用品',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['手套需成雙', '工具需可正常使用', '可接受輕微外觀痕跡'],
      priority: '緊急',
      status: '上架',
      remaining: 84,
      address: '宜蘭縣災後環境復原物資站',
      phone: '039123789',
      contactTimeWeekday: true,
      contactTimeWeekend: true,
      contactTimeMorning: true,
      contactTimeAfternoon: true,
      contactTimeEvening: true,
      note: '清潔工具請盡量分類包裝，方便志工分發。',
      image: [],
      imageFileNames: [],
      createdAt: '2026-08-25T12:30:00',
      publishedAt: '2026-08-25T12:30:00',
      expectedOffShelfAt: '2026-09-08T12:30:00',
    },
  ];

  addDemand(demand: CreateDisasterDemand) {
    this.demands.push({
      ...demand,
      id: this.demands.length + 1,
    });
  }
  getDemands() {
    return this.demands;
  }

  getDemandById(id: number): DisasterDemand | undefined {
    return this.demands.find((demand) => demand.id === id);
  }

  updateDemand(updatedDemand: DisasterDemand) {
    const index = this.demands.findIndex((item) => item.id === updatedDemand.id);

    if (index !== -1) {
      this.demands[index] = updatedDemand;
    }
  }

  deleteDemand(id: number) {
    this.demands = this.demands.filter((item) => item.id !== id);
  }
}
