import { Injectable } from '@angular/core';
import { DisasterDemand, CreateDisasterDemand } from '../../models/agency/demand';

@Injectable({
  providedIn: 'root',
})
export class DisasterDemandService {
  demands: DisasterDemand[] = [
    {
      id: 1,
      item: '成人乾糧與即食食品組',
      amount: 300,
      remaining: 280,
      unit: '份',
      amountDescription: '每份包含即食飯、罐頭、飲用水及營養補充食品，需適合災區臨時安置家庭使用。',
      category: '食物',
      reason: '因豪雨造成部分地區道路中斷，多戶家庭暫時無法取得正常餐食。',
      description: '希望募集保存期限較長且方便攜帶的食品，優先提供給災區弱勢家庭、老人及行動不便者使用。',
      brand: '不限品牌，但需確認食品包裝完整且未過期。',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需有完整食品標示'],
      priority: '非常緊急',
      status: '上架',
      createdAt: '2026-08-01T10:00:00',
      messageCount: 5,
      address: '花蓮縣花蓮市中央路三段',
      phone: '03-8230000',
      note: '請於每日09:00至17:00送達。',
      serviceTargets: {
        老人: true,
        嬰幼兒: false,
        孩童: true,
        青少年: false,
        身障: true,
        貧困: true,
        重症照護: false,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['獨居家庭'],
    },

    {
      id: 2,
      item: '成人冬季保暖外套',
      amount: 150,
      remaining: 80,
      unit: '件',
      amountDescription: '男女皆可使用，以M至XL尺寸為主。',
      category: '衣物',
      reason: '寒流造成低收入戶家庭保暖用品不足。',
      description: '需要乾淨且狀況良好的冬季外套，希望協助沒有足夠禦寒衣物的家庭。',
      brand: '不限品牌',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '',
        毀損: '不接受',
      },
      customConditions: ['需清洗乾淨'],
      priority: '緊急',
      status: '上架',
      createdAt: '2026-08-02T09:30:00',
      messageCount: 3,
      address: '台北市萬華區',
      phone: '02-23000000',
      note: '可接受郵寄。',
      serviceTargets: {
        老人: true,
        嬰幼兒: false,
        孩童: true,
        青少年: true,
        身障: false,
        貧困: true,
        重症照護: false,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['街友家庭'],
    },

    {
      id: 3,
      item: '成人醫療口罩',
      amount: 5000,
      remaining: 3500,
      unit: '個',
      amountDescription: '需符合一般醫療防護需求。',
      category: '醫療',
      reason: '災後清理環境需要大量防護用品。',
      description: '因災區清潔工作產生大量粉塵，希望募集醫療口罩供志工及居民使用。',
      brand: '不限品牌',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['有效期限至少半年'],
      priority: '緊急',
      status: '上架',
      createdAt: '2026-08-03T14:00:00',
      messageCount: 12,
      address: '台南市安南區',
      phone: '06-2550000',
      note: '',
      serviceTargets: {
        老人: false,
        嬰幼兒: false,
        孩童: false,
        青少年: false,
        身障: false,
        貧困: true,
        重症照護: true,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['災後清潔志工'],
    },

    {
      id: 4,
      item: '嬰幼兒奶粉',
      amount: 100,
      remaining: 65,
      unit: '罐',
      amountDescription: '適合0至1歲嬰幼兒使用。',
      category: '嬰幼兒',
      reason: '部分受災家庭嬰幼兒用品不足。',
      description: '希望募集未拆封奶粉，需確認保存期限充足，提供給育兒家庭使用。',
      brand: '不限品牌',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['保存期限一年以上'],
      priority: '非常緊急',
      status: '隱藏',
      messageCount: 0,
      address: '高雄市鳳山區',
      phone: '07-7000000',
      note: '目前尚未公開募集。',
      serviceTargets: {
        老人: false,
        嬰幼兒: true,
        孩童: true,
        青少年: false,
        身障: false,
        貧困: true,
        重症照護: false,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['育兒家庭'],
    },

    {
      id: 5,
      item: '毛毯與保暖棉被',
      amount: 200,
      remaining: 120,
      unit: '件',
      amountDescription: '單件尺寸需適合成人使用。',
      category: '生活用品',
      reason: '冬季低溫導致避難家庭缺少保暖用品。',
      description: '需要乾淨完整毛毯及棉被，提供給臨時安置中心使用。',
      brand: '',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '',
        毀損: '不接受',
      },
      customConditions: ['不可有明顯異味'],
      priority: '普通',
      status: '下架',
      createdAt: '2026-07-20T12:00:00',
      messageCount: 8,
      address: '宜蘭縣羅東鎮',
      phone: '03-9540000',
      note: '需求已暫時補足。',
      serviceTargets: {
        老人: true,
        嬰幼兒: true,
        孩童: true,
        青少年: false,
        身障: true,
        貧困: true,
        重症照護: false,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['臨時安置戶'],
    },
    {
      id: 6,
      item: '災區飲用水補給組合包',
      amount: 1000,
      remaining: 760,
      unit: '箱',
      amountDescription: '每箱24瓶，每瓶1500毫升，適合家庭及避難中心使用。',
      category: '食物',
      reason: '地震造成部分地區供水設備損壞，需要大量乾淨飲用水。',
      description: '希望募集大量未開封飲用水，提供災區居民、救援人員及臨時收容中心使用，需確認包裝完整且無破損。',
      brand: '不限品牌，需符合食品安全規範。',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['有效期限至少三個月'],
      priority: '非常緊急',
      status: '下架',
      createdAt: '2026-08-04T08:30:00',
      messageCount: 15,
      address: '嘉義縣阿里山鄉',
      phone: '05-2670000',
      note: '大型物資車可直接進入。',
      serviceTargets: {
        老人: true,
        嬰幼兒: true,
        孩童: true,
        青少年: true,
        身障: true,
        貧困: true,
        重症照護: true,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['災民家庭'],
    },

    {
      id: 7,
      item: '成人長袖衣物',
      amount: 400,
      remaining: 250,
      unit: '件',
      amountDescription: '男女尺寸皆可，主要需求為成人尺寸。',
      category: '衣物',
      reason: '颱風災害後居民衣物遭浸水損壞。',
      description: '募集乾淨長袖衣物，二手衣物可接受，但希望沒有破損、污漬及異味。',
      brand: '不限品牌',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '',
        毀損: '不接受',
      },
      customConditions: ['男女皆可'],
      priority: '緊急',
      status: '上架',
      createdAt: '2026-08-04T11:00:00',
      messageCount: 7,
      address: '屏東縣東港鎮',
      phone: '08-8320000',
      note: '',
      serviceTargets: {
        老人: true,
        嬰幼兒: false,
        孩童: false,
        青少年: true,
        身障: false,
        貧困: true,
        重症照護: false,
        寵物: false,
        流浪: true,
        野生: false,
      },
      customServiceTargets: ['街友'],
    },

    {
      id: 8,
      item: '慢性病患者常用藥品收納盒',
      amount: 80,
      remaining: 50,
      unit: '個',
      amountDescription: '需方便分類每日藥物。',
      category: '醫療',
      reason: '協助災後慢性病患者整理藥物。',
      description: '部分長者因搬遷至避難中心，藥物管理不便，需要簡易藥盒協助分類。',
      brand: '',
      conditions: {
        全新: '接受',
        二手: '',
        有擦痕: '',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需可清洗'],
      priority: '普通',
      status: '下架',
      createdAt: '2026-08-01T16:20:00',
      messageCount: 2,
      address: '新竹縣尖石鄉',
      phone: '03-5840000',
      note: '',
      serviceTargets: {
        老人: true,
        嬰幼兒: false,
        孩童: false,
        青少年: false,
        身障: true,
        貧困: false,
        重症照護: true,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['慢性病患者'],
    },

    {
      id: 9,
      item: '兒童書籍與學用品',
      amount: 300,
      remaining: 180,
      unit: '組',
      amountDescription: '包含鉛筆、筆記本、彩色筆及兒童讀物。',
      category: '其他',
      reason: '災後部分家庭孩童學習用品遺失。',
      description: '希望募集適合國小至國中的學用品，協助受災家庭孩童恢復正常學習。',
      brand: '不限品牌',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '',
        毀損: '不接受',
      },
      customConditions: ['內容物需完整'],
      priority: '普通',
      status: '上架',
      createdAt: '2026-08-02T13:00:00',
      messageCount: 4,
      address: '台中市和平區',
      phone: '04-2590000',
      note: '',
      serviceTargets: {
        老人: false,
        嬰幼兒: false,
        孩童: true,
        青少年: true,
        身障: false,
        貧困: true,
        重症照護: false,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['弱勢學生'],
    },

    {
      id: 10,
      item: '寵物飼料',
      amount: 200,
      remaining: 100,
      unit: '包',
      amountDescription: '犬貓皆可使用，以乾糧為主。',
      category: '其他',
      reason: '協助災區受困民眾照顧伴侶動物。',
      description: '因部分家庭撤離時無法攜帶足夠寵物用品，希望募集安全乾糧。',
      brand: '不限品牌',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需標示保存期限'],
      priority: '緊急',
      status: '隱藏',
      messageCount: 6,
      address: '台東縣成功鎮',
      phone: '089-850000',
      note: '',
      serviceTargets: {
        老人: false,
        嬰幼兒: false,
        孩童: false,
        青少年: false,
        身障: false,
        貧困: false,
        重症照護: false,
        寵物: true,
        流浪: true,
        野生: false,
      },
      customServiceTargets: ['受災飼主'],
    },
    {
      id: 11,
      item: '災區飲用水補給組合包',
      amount: 1000,
      remaining: 760,
      unit: '箱',
      amountDescription: '每箱24瓶，每瓶1500毫升，適合家庭及避難中心使用。',
      category: '食物',
      reason: '地震造成部分地區供水設備損壞，需要大量乾淨飲用水。',
      description: '希望募集大量未開封飲用水，提供災區居民、救援人員及臨時收容中心使用，需確認包裝完整且無破損。',
      brand: '不限品牌，需符合食品安全規範。',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['有效期限至少三個月'],
      priority: '非常緊急',
      status: '下架',
      createdAt: '2026-08-04T08:30:00',
      messageCount: 15,
      address: '嘉義縣阿里山鄉',
      phone: '05-2670000',
      note: '大型物資車可直接進入。',
      serviceTargets: {
        老人: true,
        嬰幼兒: true,
        孩童: true,
        青少年: true,
        身障: true,
        貧困: true,
        重症照護: true,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['災民家庭'],
    },

    {
      id: 12,
      item: '成人長袖衣物',
      amount: 400,
      remaining: 250,
      unit: '件',
      amountDescription: '男女尺寸皆可，主要需求為成人尺寸。',
      category: '衣物',
      reason: '颱風災害後居民衣物遭浸水損壞。',
      description: '募集乾淨長袖衣物，二手衣物可接受，但希望沒有破損、污漬及異味。',
      brand: '不限品牌',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '',
        毀損: '不接受',
      },
      customConditions: ['男女皆可'],
      priority: '緊急',
      status: '隱藏',
      messageCount: 7,
      address: '屏東縣東港鎮',
      phone: '08-8320000',
      note: '',
      serviceTargets: {
        老人: true,
        嬰幼兒: false,
        孩童: false,
        青少年: true,
        身障: false,
        貧困: true,
        重症照護: false,
        寵物: false,
        流浪: true,
        野生: false,
      },
      customServiceTargets: ['街友'],
    },

    {
      id: 13,
      item: '慢性病患者常用藥品收納盒',
      amount: 80,
      remaining: 50,
      unit: '個',
      amountDescription: '需方便分類每日藥物。',
      category: '醫療',
      reason: '協助災後慢性病患者整理藥物。',
      description: '部分長者因搬遷至避難中心，藥物管理不便，需要簡易藥盒協助分類。',
      brand: '',
      conditions: {
        全新: '接受',
        二手: '',
        有擦痕: '',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需可清洗'],
      priority: '普通',
      status: '上架',
      createdAt: '2026-08-01T16:20:00',
      messageCount: 2,
      address: '新竹縣尖石鄉',
      phone: '03-5840000',
      note: '',
      serviceTargets: {
        老人: true,
        嬰幼兒: false,
        孩童: false,
        青少年: false,
        身障: true,
        貧困: false,
        重症照護: true,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['慢性病患者'],
    },

    {
      id: 14,
      item: '兒童書籍與學用品',
      amount: 300,
      remaining: 180,
      unit: '組',
      amountDescription: '包含鉛筆、筆記本、彩色筆及兒童讀物。',
      category: '其他',
      reason: '災後部分家庭孩童學習用品遺失。',
      description: '希望募集適合國小至國中的學用品，協助受災家庭孩童恢復正常學習。',
      brand: '不限品牌',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '',
        毀損: '不接受',
      },
      customConditions: ['內容物需完整'],
      priority: '普通',
      status: '下架',
      createdAt: '2026-08-02T13:00:00',
      messageCount: 4,
      address: '台中市和平區',
      phone: '04-2590000',
      note: '',
      serviceTargets: {
        老人: false,
        嬰幼兒: false,
        孩童: true,
        青少年: true,
        身障: false,
        貧困: true,
        重症照護: false,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['弱勢學生'],
    },

    {
      id: 15,
      item: '寵物飼料',
      amount: 200,
      remaining: 100,
      unit: '包',
      amountDescription: '犬貓皆可使用，以乾糧為主。',
      category: '其他',
      reason: '協助災區受困民眾照顧伴侶動物。',
      description: '因部分家庭撤離時無法攜帶足夠寵物用品，希望募集安全乾糧。',
      brand: '不限品牌',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需標示保存期限'],
      priority: '緊急',
      status: '隱藏',
      messageCount: 6,
      address: '台東縣成功鎮',
      phone: '089-850000',
      note: '',
      serviceTargets: {
        老人: false,
        嬰幼兒: false,
        孩童: false,
        青少年: false,
        身障: false,
        貧困: false,
        重症照護: false,
        寵物: true,
        流浪: true,
        野生: false,
      },
      customServiceTargets: ['受災飼主'],
    },
    {
      id: 16,
      item: '災區臨時安置家庭急需大型綜合生活補給物資組合包（包含成人與兒童使用之日常生活用品、清潔用品、簡易餐具、衛生用品、照明用品以及其他因災害造成家庭生活中斷後所需要補充的基本用品）',
      amount: 50,
      remaining: 50,
      unit: '組',
      amountDescription: '每組提供一戶受災家庭約一週生活所需用品。',
      category: '生活用品',
      reason: '因大型災害造成住宅損壞，多戶家庭暫時無法返回原居住地，需要基本生活物資協助。',
      description: '希望募集完整生活補給組合包，內容包含家庭日常所需用品，需適合老人、孩童及身心障礙者使用，並希望物品皆保持良好狀態。',
      brand: '不限品牌，但需符合安全及品質要求。',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需分類包裝', '大型物品請先聯絡確認'],
      priority: '非常緊急',
      status: '上架',
      createdAt: '2026-08-06T09:00:00',
      messageCount: 20,
      address: '高雄市旗山區',
      phone: '07-6600000',
      note: '此需求為災後大型家庭補給專案，若一次提供大量物資請提前聯繫，以方便安排倉儲空間、分類整理以及後續配送流程。',
      serviceTargets: {
        老人: true,
        嬰幼兒: true,
        孩童: true,
        青少年: true,
        身障: true,
        貧困: true,
        重症照護: false,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['災後失去住所家庭'],
    },
    {
      id: 17,
      item: '災區兒童臨時照護玩具與心理安撫用品組',
      amount: 120,
      remaining: 45,
      unit: '組',
      amountDescription: '每組包含繪本、益智玩具、彩色筆及簡易遊戲用品。',
      category: '嬰幼兒',
      reason: '災害期間部分兒童因生活環境改變產生不安，需要透過活動用品協助情緒安撫。',
      description: '募集適合幼兒及兒童使用的安全玩具與閱讀用品，希望協助臨時安置中心提供安心的活動空間。',
      brand: '不限品牌，需符合兒童用品安全標準。',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '',
        毀損: '不接受',
      },
      customConditions: ['不可有尖銳零件'],
      priority: '緊急',
      status: '上架',
      createdAt: '2026-08-04T15:30:00',
      messageCount: 9,
      address: '苗栗縣南庄鄉',
      phone: '037-823000',
      note: '若為二手用品請先清潔消毒。',
      serviceTargets: {
        老人: false,
        嬰幼兒: true,
        孩童: true,
        青少年: false,
        身障: false,
        貧困: true,
        重症照護: false,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['安置中心兒童'],
    },

    {
      id: 18,
      item: '身心障礙者專用輔助用品與生活支援設備',
      amount: 60,
      remaining: 22,
      unit: '件',
      amountDescription: '包含助行用品、防滑用品及日常生活輔助設備。',
      category: '醫療',
      reason: '部分身心障礙居民因災害造成原有輔具損壞，需要緊急替代用品。',
      description: '希望募集適合身心障礙者使用的輔助用品，需確認功能正常，方便受災民眾恢復日常生活。',
      brand: '不限品牌，可接受不同規格型號。',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '',
        毀損: '不接受',
      },
      customConditions: ['需附使用說明'],
      priority: '非常緊急',
      status: '隱藏',
      messageCount: 14,
      address: '南投縣埔里鎮',
      phone: '049-2900000',
      note: '大型輔具請提前預約搬運。',
      serviceTargets: {
        老人: true,
        嬰幼兒: false,
        孩童: false,
        青少年: false,
        身障: true,
        貧困: true,
        重症照護: true,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['行動不便居民'],
    },

    {
      id: 19,
      item: '災後環境清潔消毒用品補充需求',
      amount: 300,
      remaining: 0,
      unit: '組',
      amountDescription: '每組包含垃圾袋、清潔劑、手套、刷具及消毒用品。',
      category: '生活用品',
      reason: '災後家園清理工作完成，目前物資需求已達標。',
      description: '此需求原用於協助居民進行環境整理，目前剩餘數量為零，保留資料供後續需求紀錄與統計使用。',
      brand: '',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需具有完整包裝'],
      priority: '普通',
      status: '下架',
      createdAt: '2026-07-25T10:30:00',
      messageCount: 30,
      address: '新北市瑞芳區',
      phone: '02-24970000',
      note: '需求已完成，因此暫停募集。',
      serviceTargets: {
        老人: true,
        嬰幼兒: false,
        孩童: false,
        青少年: false,
        身障: true,
        貧困: true,
        重症照護: false,
        寵物: false,
        流浪: false,
        野生: false,
      },
      customServiceTargets: ['災後清潔家庭'],
    },

    {
      id: 20,
      item: '野生動物救援臨時收容所專用飼料與醫療照護用品',
      amount: 150,
      remaining: 90,
      unit: '箱',
      amountDescription: '包含動物飼料、飲水用品及基本照護用品。',
      category: '其他',
      reason: '天然災害造成野生動物棲地受損，需要協助救援與安置。',
      description: '募集提供給野生動物救援單位使用之相關用品，需確認適合動物使用且保存期限充足。',
      brand: '不限品牌，需標示成分。',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需適合多種類動物使用'],
      priority: '緊急',
      status: '隱藏',
      messageCount: 0,
      address: '花蓮縣壽豐鄉',
      phone: '03-8650000',
      note: '目前尚未公開募集，等待救援單位確認。',
      serviceTargets: {
        老人: false,
        嬰幼兒: false,
        孩童: false,
        青少年: false,
        身障: false,
        貧困: false,
        重症照護: false,
        寵物: false,
        流浪: false,
        野生: true,
      },
      customServiceTargets: ['野生動物救援中心'],
    },
  ];

  addDemand(demand: CreateDisasterDemand) {
    this.demands.push({
      ...demand,
      id: this.demands.length + 1,
    });
  }
  getDemands() {
    return this.demands;
  }

  getDemandById(id: number): DisasterDemand | undefined {
    return this.demands.find((demand) => demand.id === id);
  }

  updateDemand(updatedDemand: DisasterDemand) {
    const index = this.demands.findIndex((item) => item.id === updatedDemand.id);

    if (index !== -1) {
      this.demands[index] = updatedDemand;
    }
  }

  deleteDemand(id: number) {
    this.demands = this.demands.filter((item) => item.id !== id);
  }
}
