import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { delay } from 'rxjs/operators';
import { DisasterDemand, CreateDisasterDemand } from '../../../models/agency/disaster-demand';

@Injectable({
  providedIn: 'root',
})
export class DisasterDemandService {
  demands: DisasterDemand[] = [
    {
      serialNo: 1,
      item: '礦泉水',
      amount: 500,
      unit: '箱',
      amountDescription: '每箱24瓶，每瓶600毫升。',
      reason: '災區供水及民生物資運輸受影響，避難收容人數增加。',
      description: '以未開封且保存期限充足之瓶裝飲用水為主。',
      brand: '不限品牌',
      category: '食品與飲用水',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '不接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['保存期限至少六個月'],
      priority: '非常緊急',
      status: '上架',
      remaining: 320,
      address: '宜蘭縣災害物資集中收受中心',
      phone: '039123456',
      contactTimeDifferent: false,
      contactTimeMorning: true,
      contactTimeAfternoon: true,
      contactTimeEvening: true,
      note: '請優先協助配送至物資短缺的避難收容場所。',
      image: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD5ONgl_Kphwaa5nFr_VfHXg1Ej2CkswQyVQtNUTKsmPyT1x_3wCCwoqVl&s=10'],
      imageFileNames: ['測試圖1'],
      createdAt: '2026-08-20T09:00:00',
      publishedAt: '2026-08-20T09:00:00',
      expectedOffShelfAt: '2026-08-27T09:00:00',
    },

    {
      serialNo: 2,
      item: '即食白粥及營養粥',
      amount: 300,
      unit: '箱',
      amountDescription: '每箱約12～24份，可提供單人份即食食品。',
      reason: '部分居民無法正常使用瓦斯及電力設備，需要即食食品。',
      description: '以常溫保存、不需冷藏且容易食用之食品為佳。',
      brand: '不限品牌',
      category: '食品與飲用水',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['低鹽、低油、適合長者食用'],
      priority: '緊急',
      status: '上架',
      remaining: 180,
      address: '宜蘭縣災害物資集中收受中心',
      phone: '039234567',
      contactTimeDifferent: true,
      weekdayMorning: true,
      weekdayAfternoon: true,
      weekdayEvening: false,
      weekendMorning: false,
      weekendAfternoon: true,
      weekendEvening: false,
      note: '食品請確認保存期限及外包裝完整。',
      image: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3RSqD5lxT2gEWllJgc4AKNXx5WuH9hxR1mbbS9aT12g&s=10',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3RSqD5lxT2gEWllJgc4AKNXx5WuH9hxR1mbbS9aT12g&s=10'
      ],
      imageFileNames: ['測試圖2'],
      createdAt: '2026-08-21T10:30:00',
      publishedAt: '2026-08-21T10:30:00',
      expectedOffShelfAt: '2026-09-04T10:30:00',
    },

    {
      serialNo: 3,
      item: '成人保暖外套',
      amount: 200,
      unit: '件',
      amountDescription: '成人男女皆可穿著，以M～XL尺寸為主。',
      reason: '災後臨時安置場所夜間溫度較低。',
      description: '希望提供乾淨、完整且適合成人穿著的外套。',
      brand: '不限品牌',
      category: '衣物與保暖用品',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['請先清洗並確認無明顯異味'],
      priority: '普通',
      status: '上架',
      remaining: 125,
      address: '宜蘭縣冬山鄉臨時安置中心',
      phone: '039345678',
      contactTimeDifferent: true,
      weekdayMorning: false,
      weekdayAfternoon: true,
      weekdayEvening: true,
      weekendMorning: true,
      weekendAfternoon: true,
      weekendEvening: false,
      note: '成人男女外套皆可。',
      image: ['https://shoplineimg.com/64587ad406d620007ce10917/6a2f518ab8d8ed2696bdf42d/800x.jpg?',
        'https://media.etmall.com.tw/nximg/007837/7837541/7837541_xxl.jpg?t=22437616813',
        'https://img.pchome.com.tw/cs/items/DEBLNNA900GOLU1/000001_1695453034.jpg?',
        'https://img.pchome.com.tw/cs/items/DEBLU1A900JDAHV/i010005_1761118380.jpg',
        'https://img.pchome.com.tw/cs/items/DEBLNNA900GOZIM/000001_1700106052.jpg?width=640',
        'https://img.91app.com/webapi/imagesV3/Original/SalePage/9271978/5/639008613314930000?quality=30&v=1 '
      ],
      imageFileNames: ['測試圖3'],
      createdAt: '2026-08-22T08:30:00',
      publishedAt: '2026-08-22T08:30:00',
      expectedOffShelfAt: '2026-09-21T08:30:00',
    },

    {
      serialNo: 4,
      item: '防寒毛毯',
      amount: 350,
      unit: '條',
      amountDescription: '每條約150×200公分，方便一名成人使用。',
      reason: '臨時避難場所床位及保暖物資不足。',
      description: '尺寸不拘但以成人使用規格為佳，需保持乾燥。',
      brand: '不限品牌',
      category: '衣物與保暖用品',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['可接受輕微使用痕跡', '不可有霉味', '不可受潮'],
      priority: '非常緊急',
      status: '上架',
      remaining: 210,
      address: '宜蘭縣羅東鎮臨時避難中心',
      phone: '039456789',
      contactTimeDifferent: true,
      weekdayMorning: false,
      weekdayAfternoon: true,
      weekdayEvening: true,
      weekendMorning: false,
      weekendAfternoon: true,
      weekendEvening: true,
      note: '請保持毛毯乾燥。',
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD5ONgl_Kphwaa5nFr_VfHXg1Ej2CkswQyVQtNUTKsmPyT1x_3wCCwoqVl&s=10',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3RSqD5lxT2gEWllJgc4AKNXx5WuH9hxR1mbbS9aT12g&s=10',
      ],
      imageFileNames: ['測試圖1', '測試圖2'],
      createdAt: '2026-08-23T11:00:00',
      publishedAt: '2026-08-23T11:00:00',
      expectedOffShelfAt: '2026-08-30T11:00:00',
    },

    {
      serialNo: 5,
      item: '外傷急救包',
      amount: 100,
      unit: '組',
      amountDescription: '每組包含消毒用品、紗布、繃帶及常用急救用品。',
      reason: '災後清理環境期間需要補充現場急救用品。',
      description: '以完整未拆封之急救用品為主。',
      brand: '不限品牌，但醫療用品需有合法標示。',
      category: '醫療與照護用品',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '不接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需有清楚保存期限', '包裝需完整'],
      priority: '非常緊急',
      status: '上架',
      remaining: 38,
      address: '宜蘭縣醫療物資集中收受站',
      phone: '039567890',
      contactTimeDifferent: false,
      contactTimeMorning: true,
      contactTimeAfternoon: true,
      contactTimeEvening: true,
      note: '醫療用品請勿提供已開封產品。',
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3RSqD5lxT2gEWllJgc4AKNXx5WuH9hxR1mbbS9aT12g&s=10',
        'https://shoplineimg.com/64587ad406d620007ce10917/6a2f518ab8d8ed2696bdf42d/800x.jpg?',
      ],
      imageFileNames: ['測試圖2', '測試圖3'],
      createdAt: '2026-08-24T08:00:00',
      publishedAt: '2026-08-24T08:00:00',
      expectedOffShelfAt: '2026-08-31T08:00:00',
    },

    {
      serialNo: 6,
      item: '成人紙尿褲 M 號',
      amount: 80,
      unit: '箱',
      amountDescription: '成人M號，每箱約8～12包。',
      reason: '部分受災長者及行動不便居民需要照護用品。',
      description: '希望提供成人紙尿褲M號，包裝需完整。',
      brand: '不限品牌',
      category: '醫療與照護用品',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '不接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['M號優先', '需有獨立包裝'],
      priority: '緊急',
      status: '上架',
      remaining: 47,
      address: '宜蘭縣長者照護物資站',
      phone: '039678901',
      contactTimeDifferent: true,
      weekdayMorning: true,
      weekdayAfternoon: true,
      weekdayEvening: false,
      weekendMorning: false,
      weekendAfternoon: false,
      weekendEvening: false,
      note: '請勿提供已拆封或受潮產品。',
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD5ONgl_Kphwaa5nFr_VfHXg1Ej2CkswQyVQtNUTKsmPyT1x_3wCCwoqVl&s=10',
        'https://shoplineimg.com/64587ad406d620007ce10917/6a2f518ab8d8ed2696bdf42d/800x.jpg?',
      ],
      imageFileNames: ['測試圖1', '測試圖3'],
      createdAt: '2026-08-24T13:00:00',
      publishedAt: '2026-08-24T13:00:00',
      expectedOffShelfAt: '2026-09-07T13:00:00',
    },

    {
      serialNo: 7,
      item: '酒精濕紙巾',
      amount: 500,
      unit: '包',
      amountDescription: '每包至少20～30抽。',
      reason: '災後公共空間人員集中，需要加強清潔。',
      description: '以完整包裝、未過期之酒精濕紙巾為主。',
      brand: '不限品牌',
      category: '清潔與衛生用品',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '接受',
      },
      customConditions: ['酒精成分需清楚標示', '不可有明顯乾涸'],
      priority: '緊急',
      status: '上架',
      remaining: 290,
      address: '宜蘭縣災後清潔物資站',
      phone: '039789012',
      contactTimeDifferent: false,
      contactTimeMorning: true,
      contactTimeAfternoon: true,
      contactTimeEvening: false,
      note: '請確認包裝沒有破損。',
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD5ONgl_Kphwaa5nFr_VfHXg1Ej2CkswQyVQtNUTKsmPyT1x_3wCCwoqVl&s=10',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3RSqD5lxT2gEWllJgc4AKNXx5WuH9hxR1mbbS9aT12g&s=10',
        'https://shoplineimg.com/64587ad406d620007ce10917/6a2f518ab8d8ed2696bdf42d/800x.jpg?',
      ],
      imageFileNames: ['測試圖1', '測試圖2', '測試圖3'],
      createdAt: '2026-08-24T14:00:00',
      publishedAt: '2026-08-24T14:00:00',
      expectedOffShelfAt: '2026-09-07T14:00:00',
    },

    {
      serialNo: 8,
      item: '嬰兒紙尿布 M 號',
      amount: 120,
      unit: '箱',
      amountDescription: '嬰兒M號紙尿布，每箱約3～4包。',
      reason: '避難收容場所目前有多名嬰幼兒家庭。',
      description: '以未拆封、保存完整的嬰兒紙尿布為主。',
      brand: '不限品牌',
      category: '嬰幼兒用品',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '不接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['M號優先', '需適合嬰幼兒肌膚使用'],
      priority: '非常緊急',
      status: '上架',
      remaining: 56,
      address: '宜蘭縣嬰幼兒臨時照護中心',
      phone: '039890123',
      contactTimeDifferent: false,
      contactTimeMorning: true,
      contactTimeAfternoon: true,
      contactTimeEvening: true,
      note: '請以未拆封產品為主。',
      image: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3RSqD5lxT2gEWllJgc4AKNXx5WuH9hxR1mbbS9aT12g&s=10'],
      imageFileNames: ['測試圖2'],
      createdAt: '2026-08-25T08:00:00',
      publishedAt: '2026-08-25T08:00:00',
      expectedOffShelfAt: '2026-09-01T08:00:00',
    },

    {
      serialNo: 9,
      item: '成人紙尿褲 L 號',
      amount: 150,
      unit: '箱',
      amountDescription: '成人L號，每箱約8～12包。',
      reason: '目前收容長者照護用品暫時充足。',
      description: '目前暫不急需補充，保留需求資料供後續調度。',
      brand: '不限品牌',
      category: '長者與身心障礙用品',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '不接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['L號優先'],
      priority: '緊急',
      status: '隱藏',
      remaining: 150,
      address: '宜蘭縣長者照護物資站',
      phone: '039901234',
      contactTimeDifferent: true,
      weekdayMorning: true,
      weekdayAfternoon: true,
      weekdayEvening: false,
      weekendMorning: false,
      weekendAfternoon: false,
      weekendEvening: false,
      note: '目前暫停募集。',
      image: ['https://shoplineimg.com/64587ad406d620007ce10917/6a2f518ab8d8ed2696bdf42d/800x.jpg?'],
      imageFileNames: ['測試圖3'],
      createdAt: '2026-08-18T09:00:00',
    },

    {
      serialNo: 10,
      item: '女性生理用品衛生棉',
      amount: 100,
      unit: '箱',
      amountDescription: '日用及夜用衛生棉皆可。',
      reason: '災害撤離後部分女性未能攜帶足夠個人衛生用品。',
      description: '以獨立包裝、未拆封、未過期產品為主。',
      brand: '不限品牌',
      category: '女性生理用品',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '不接受',
        過期: '不接受',
        毀損: '接受',
      },
      customConditions: ['日用與夜用皆可', '獨立包裝優先'],
      priority: '緊急',
      status: '上架',
      remaining: 62,
      address: '宜蘭縣婦女物資收受站',
      phone: '039012345',
      contactTimeDifferent: true,
      weekdayMorning: false,
      weekdayAfternoon: true,
      weekdayEvening: true,
      weekendMorning: true,
      weekendAfternoon: true,
      weekendEvening: false,
      note: '請將日用與夜用產品分開標示。',
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD5ONgl_Kphwaa5nFr_VfHXg1Ej2CkswQyVQtNUTKsmPyT1x_3wCCwoqVl&s=10',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3RSqD5lxT2gEWllJgc4AKNXx5WuH9hxR1mbbS9aT12g&s=10',
      ],
      imageFileNames: ['測試圖1', '測試圖2'],
      createdAt: '2026-08-25T09:00:00',
      publishedAt: '2026-08-25T09:00:00',
      expectedOffShelfAt: '2026-09-08T09:00:00',
    },

    {
      serialNo: 11,
      item: '狗飼料',
      amount: 100,
      unit: '袋',
      amountDescription: '成犬乾飼料，每袋約10～15公斤。',
      reason: '災後部分飼主帶著寵物撤離，需要補充犬隻飼料。',
      description: '以成犬乾飼料為主，不得過期或包裝破損。',
      brand: '不限品牌',
      category: '寵物與動物用品',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['成犬飼料優先', '不可有受潮情形'],
      priority: '普通',
      status: '上架',
      remaining: 73,
      address: '宜蘭縣流浪動物臨時安置站',
      phone: '039123678',
      contactTimeDifferent: true,
      weekdayMorning: false,
      weekdayAfternoon: true,
      weekdayEvening: true,
      weekendMorning: false,
      weekendAfternoon: true,
      weekendEvening: true,
      note: '請標示飼料適用犬隻年齡。',
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3RSqD5lxT2gEWllJgc4AKNXx5WuH9hxR1mbbS9aT12g&s=10',
        'https://shoplineimg.com/64587ad406d620007ce10917/6a2f518ab8d8ed2696bdf42d/800x.jpg?',
      ],
      imageFileNames: ['測試圖2', '測試圖3'],
      createdAt: '2026-08-24T15:00:00',
      publishedAt: '2026-08-24T15:00:00',
      expectedOffShelfAt: '2026-09-23T15:00:00',
    },

    {
      serialNo: 12,
      item: 'LED 手電筒',
      amount: 250,
      unit: '支',
      amountDescription: '攜帶式LED手電筒，每支需可正常照明。',
      reason: '部分災區停電，居民夜間移動缺乏照明設備。',
      description: '以攜帶方便、操作簡單且可使用一般電池的手電筒為佳。',
      brand: '不限品牌',
      category: '防災與照明用品',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需附電池', '可接受輕微外觀刮痕'],
      priority: '非常緊急',
      status: '上架',
      remaining: 90,
      address: '宜蘭縣災害防災物資站',
      phone: '039234678',
      contactTimeDifferent: true,
      weekdayMorning: false,
      weekdayAfternoon: true,
      weekdayEvening: true,
      weekendMorning: true,
      weekendAfternoon: true,
      weekendEvening: true,
      note: '請確認每支手電筒均可正常使用。',
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD5ONgl_Kphwaa5nFr_VfHXg1Ej2CkswQyVQtNUTKsmPyT1x_3wCCwoqVl&s=10',
        'https://shoplineimg.com/64587ad406d620007ce10917/6a2f518ab8d8ed2696bdf42d/800x.jpg?',
      ],
      imageFileNames: ['測試圖1', '測試圖3'],
      createdAt: '2026-08-25T10:00:00',
      publishedAt: '2026-08-25T10:00:00',
      expectedOffShelfAt: '2026-09-01T10:00:00',
    },

    {
      serialNo: 13,
      item: '行動電源',
      amount: 150,
      unit: '個',
      amountDescription: '容量10,000mAh以上之行動電源。',
      reason: '災區停電影響手機及通訊設備充電。',
      description: '希望提供容量足夠且可正常充放電之行動電源。',
      brand: '不限品牌，但需確認產品安全性。',
      category: '通訊與求救用品',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '不接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['容量至少10000mAh', '需可正常充電', '需附充電線'],
      priority: '非常緊急',
      status: '上架',
      remaining: 42,
      address: '宜蘭縣災害通訊物資站',
      phone: '039345678',
      contactTimeDifferent: false,
      contactTimeMorning: true,
      contactTimeAfternoon: true,
      contactTimeEvening: true,
      note: '請確認行動電源沒有異常狀況。',
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD5ONgl_Kphwaa5nFr_VfHXg1Ej2CkswQyVQtNUTKsmPyT1x_3wCCwoqVl&s=10',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3RSqD5lxT2gEWllJgc4AKNXx5WuH9hxR1mbbS9aT12g&s=10',
        'https://shoplineimg.com/64587ad406d620007ce10917/6a2f518ab8d8ed2696bdf42d/800x.jpg?',
      ],
      imageFileNames: ['測試圖1', '測試圖2', '測試圖3'],
      createdAt: '2026-08-25T10:30:00',
      publishedAt: '2026-08-25T10:30:00',
      expectedOffShelfAt: '2026-09-01T10:30:00',
    },

    {
      serialNo: 14,
      item: '卡式瓦斯爐',
      amount: 80,
      unit: '台',
      amountDescription: '家用攜帶式卡式瓦斯爐。',
      reason: '部分地區電力及固定瓦斯供應尚未恢復。',
      description: '以功能正常、結構完整之設備為主。',
      brand: '不限品牌',
      category: '生活與炊事用品',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需確認點火功能正常', '不可有瓦斯洩漏問題'],
      priority: '緊急',
      status: '上架',
      remaining: 31,
      address: '宜蘭縣災害生活物資站',
      phone: '039456789',
      contactTimeDifferent: true,
      weekdayMorning: true,
      weekdayAfternoon: true,
      weekdayEvening: false,
      weekendMorning: false,
      weekendAfternoon: true,
      weekendEvening: false,
      note: '二手設備需先確認安全性。',
      image: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD5ONgl_Kphwaa5nFr_VfHXg1Ej2CkswQyVQtNUTKsmPyT1x_3wCCwoqVl&s=10'],
      imageFileNames: ['測試圖1'],
      createdAt: '2026-08-24T16:00:00',
      publishedAt: '2026-08-24T16:00:00',
      expectedOffShelfAt: '2026-09-07T16:00:00',
    },

    {
      serialNo: 15,
      item: '臨時居住帳篷',
      amount: 50,
      unit: '頂',
      amountDescription: '至少可供2～4人臨時休息使用之防水帳篷。',
      reason: '部分受災戶住宅暫時無法居住。',
      description: '希望提供完整帳篷、支架及固定配件。',
      brand: '不限品牌',
      category: '居住安置與修繕用品',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需具防水功能', '配件需完整', '可接受輕微使用痕跡', '不可有破洞', '不可嚴重發霉'],
      priority: '非常緊急',
      status: '上架',
      remaining: 18,
      address: '宜蘭縣災民臨時安置中心',
      phone: '039567890',
      contactTimeDifferent: false,
      contactTimeMorning: true,
      contactTimeAfternoon: true,
      contactTimeEvening: true,
      note: '大型物資請事先電話聯繫確認配送方式。',
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3RSqD5lxT2gEWllJgc4AKNXx5WuH9hxR1mbbS9aT12g&s=10',
        'https://shoplineimg.com/64587ad406d620007ce10917/6a2f518ab8d8ed2696bdf42d/800x.jpg?',
      ],
      imageFileNames: ['測試圖2', '測試圖3'],
      createdAt: '2026-08-25T11:00:00',
      publishedAt: '2026-08-25T11:00:00',
      expectedOffShelfAt: '2026-09-01T11:00:00',
    },

    {
      serialNo: 16,
      item: '折疊桌椅',
      amount: 60,
      unit: '組',
      amountDescription: '每組包含折疊桌1張及折疊椅4張。',
      reason: '臨時收容場所需要增加用餐及行政作業使用之桌椅。',
      description: '目前暫無立即需求，後續視收容人數重新開放。',
      brand: '不限品牌',
      category: '其他',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '接受',
      },
      customConditions: ['可接受正常使用痕跡'],
      priority: '普通',
      status: '隱藏',
      remaining: 60,
      address: '宜蘭縣臨時收容行政中心',
      phone: '039678901',
      contactTimeDifferent: true,
      weekdayMorning: false,
      weekdayAfternoon: true,
      weekdayEvening: false,
      weekendMorning: false,
      weekendAfternoon: false,
      weekendEvening: true,
      note: '目前暫停募集。',
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD5ONgl_Kphwaa5nFr_VfHXg1Ej2CkswQyVQtNUTKsmPyT1x_3wCCwoqVl&s=10',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3RSqD5lxT2gEWllJgc4AKNXx5WuH9hxR1mbbS9aT12g&s=10',
      ],
      imageFileNames: ['測試圖1', '測試圖2'],
      createdAt: '2026-08-19T10:00:00',
    },

    {
      serialNo: 17,
      item: '罐頭食品綜合箱',
      amount: 400,
      unit: '箱',
      amountDescription: '每箱約24～48罐。',
      reason: '災區部分家庭暫時無法正常烹煮。',
      description: '希望提供保存期限充足且外罐完整之罐頭食品。',
      brand: '不限品牌',
      category: '食品與飲用水',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['保存期限至少六個月', '不可有罐體膨脹'],
      priority: '普通',
      status: '上架',
      remaining: 400,
      address: '宜蘭縣災害食品物資站',
      phone: '039789012',
      contactTimeDifferent: true,
      weekdayMorning: true,
      weekdayAfternoon: true,
      weekdayEvening: false,
      weekendMorning: true,
      weekendAfternoon: true,
      weekendEvening: false,
      note: '請依食品種類分類裝箱。',
      image: ['https://shoplineimg.com/64587ad406d620007ce10917/6a2f518ab8d8ed2696bdf42d/800x.jpg?'],
      imageFileNames: ['測試圖3'],
      createdAt: '2026-08-25T11:30:00',
      publishedAt: '2026-08-25T11:30:00',
      expectedOffShelfAt: '2026-09-24T11:30:00',
    },

    {
      serialNo: 18,
      item: '防水帆布及修繕材料',
      amount: 100,
      unit: '組',
      amountDescription: '每組包含防水帆布、固定繩、束帶及基本修繕用品。',
      reason: '部分民宅屋頂及門窗於災害中受損。',
      description: '防水帆布尺寸以3×4公尺以上為佳。',
      brand: '不限品牌',
      category: '居住安置與修繕用品',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['需具基本防水功能', '不可有破洞'],
      priority: '緊急',
      status: '上架',
      remaining: 27,
      address: '宜蘭縣災後住宅修繕物資站',
      phone: '039890123',
      contactTimeDifferent: false,
      contactTimeMorning: true,
      contactTimeAfternoon: true,
      contactTimeEvening: true,
      note: '大型帆布請事前聯絡，以便安排搬運。',
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD5ONgl_Kphwaa5nFr_VfHXg1Ej2CkswQyVQtNUTKsmPyT1x_3wCCwoqVl&s=10',
        'https://shoplineimg.com/64587ad406d620007ce10917/6a2f518ab8d8ed2696bdf42d/800x.jpg?',
      ],
      imageFileNames: ['測試圖1', '測試圖3'],
      createdAt: '2026-08-25T12:00:00',
      publishedAt: '2026-08-25T12:00:00',
      expectedOffShelfAt: '2026-09-08T12:00:00',
    },

    {
      serialNo: 19,
      item: '緊急醫療照護用品綜合包',
      amount: 75,
      unit: '組',
      amountDescription: '每組包含紗布、繃帶、醫療膠帶及消毒用品。',
      reason: '目前醫療照護用品已募集足夠數量。',
      description: '本筆需求已完成階段性物資募集。',
      brand: '不限品牌',
      category: '醫療與照護用品',
      conditions: {
        全新: '接受',
        二手: '不接受',
        有擦痕: '不接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['醫療耗材需有完整標示'],
      priority: '非常緊急',
      status: '下架',
      remaining: 0,
      address: '宜蘭縣醫療物資集中收受站',
      phone: '039012678',
      contactTimeDifferent: true,
      weekdayMorning: true,
      weekdayAfternoon: true,
      weekdayEvening: false,
      weekendMorning: false,
      weekendAfternoon: false,
      weekendEvening: false,
      note: '本筆需求已完成募集。',
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3RSqD5lxT2gEWllJgc4AKNXx5WuH9hxR1mbbS9aT12g&s=10',
        'https://shoplineimg.com/64587ad406d620007ce10917/6a2f518ab8d8ed2696bdf42d/800x.jpg?',
      ],
      imageFileNames: ['測試圖2', '測試圖3'],
      createdAt: '2026-08-18T08:00:00',
      publishedAt: '2026-08-18T08:00:00',
      expectedOffShelfAt: '2026-08-25T13:00:00',
    },

    {
      serialNo: 20,
      item: '災後環境清潔用品綜合組',
      amount: 200,
      unit: '組',
      amountDescription: '每組包含垃圾袋、掃把、畚箕、手套、抹布及清潔用品。',
      reason: '災後環境整理產生大量垃圾及泥沙。',
      description: '希望提供耐用且容易清洗之清潔工具。',
      brand: '不限品牌',
      category: '清潔與衛生用品',
      conditions: {
        全新: '接受',
        二手: '接受',
        有擦痕: '接受',
        過期: '不接受',
        毀損: '不接受',
      },
      customConditions: ['手套需成雙', '工具需可正常使用', '可接受輕微外觀痕跡'],
      priority: '緊急',
      status: '上架',
      remaining: 84,
      address: '宜蘭縣災後環境復原物資站',
      phone: '039123789',
      contactTimeDifferent: false,
      contactTimeMorning: true,
      contactTimeAfternoon: true,
      contactTimeEvening: true,
      note: '清潔工具請盡量分類包裝。',
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD5ONgl_Kphwaa5nFr_VfHXg1Ej2CkswQyVQtNUTKsmPyT1x_3wCCwoqVl&s=10',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3RSqD5lxT2gEWllJgc4AKNXx5WuH9hxR1mbbS9aT12g&s=10',
        'https://shoplineimg.com/64587ad406d620007ce10917/6a2f518ab8d8ed2696bdf42d/800x.jpg?',
      ],
      imageFileNames: ['測試圖1', '測試圖2', '測試圖3'],
      createdAt: '2026-08-25T12:30:00',
      publishedAt: '2026-08-25T12:30:00',
      expectedOffShelfAt: '2026-09-08T12:30:00',
    },
  ];

  addDemand(demand: CreateDisasterDemand) {
    this.demands.push({
      ...demand,
      serialNo: this.demands.length + 1,
    });
  }

  getDemands() {
    return this.demands;
  }

  getDemandsFromServer(): Observable<DisasterDemand[]> {
    return of(this.demands).pipe(delay(3000));
  }

  getDemandBySerialNo(serialNo: number): DisasterDemand | undefined {
    return this.demands.find((demand) => demand.serialNo === serialNo);
  }

  updateDemand(updatedDemand: DisasterDemand) {
    const index = this.demands.findIndex((item) => item.serialNo === updatedDemand.serialNo);

    if (index !== -1) {
      this.demands[index] = updatedDemand;
    }
  }

  deleteDemand(serialNo: number) {
    this.demands = this.demands.filter((item) => item.serialNo !== serialNo);
  }
}
